package com.maelook.daoBean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.maelook.Bean.continues;
import com.maelook.Bean.flash;
import com.maelook.Bean.multi;
import com.maelook.Bean.single;

import com.maelook.daoBean.continuesDao;
import com.maelook.daoBean.flashDao;
import com.maelook.daoBean.multiDao;
import com.maelook.daoBean.singleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig continuesDaoConfig;
    private final DaoConfig flashDaoConfig;
    private final DaoConfig multiDaoConfig;
    private final DaoConfig singleDaoConfig;

    private final continuesDao continuesDao;
    private final flashDao flashDao;
    private final multiDao multiDao;
    private final singleDao singleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        continuesDaoConfig = daoConfigMap.get(continuesDao.class).clone();
        continuesDaoConfig.initIdentityScope(type);

        flashDaoConfig = daoConfigMap.get(flashDao.class).clone();
        flashDaoConfig.initIdentityScope(type);

        multiDaoConfig = daoConfigMap.get(multiDao.class).clone();
        multiDaoConfig.initIdentityScope(type);

        singleDaoConfig = daoConfigMap.get(singleDao.class).clone();
        singleDaoConfig.initIdentityScope(type);

        continuesDao = new continuesDao(continuesDaoConfig, this);
        flashDao = new flashDao(flashDaoConfig, this);
        multiDao = new multiDao(multiDaoConfig, this);
        singleDao = new singleDao(singleDaoConfig, this);

        registerDao(continues.class, continuesDao);
        registerDao(flash.class, flashDao);
        registerDao(multi.class, multiDao);
        registerDao(single.class, singleDao);
    }
    
    public void clear() {
        continuesDaoConfig.clearIdentityScope();
        flashDaoConfig.clearIdentityScope();
        multiDaoConfig.clearIdentityScope();
        singleDaoConfig.clearIdentityScope();
    }

    public continuesDao getContinuesDao() {
        return continuesDao;
    }

    public flashDao getFlashDao() {
        return flashDao;
    }

    public multiDao getMultiDao() {
        return multiDao;
    }

    public singleDao getSingleDao() {
        return singleDao;
    }

}
