package com.maelook.daoBean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.maelook.Bean.singleRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SINGLE_RECORD".
*/
public class singleRecordDao extends AbstractDao<singleRecord, String> {

    public static final String TABLENAME = "SINGLE_RECORD";

    /**
     * Properties of entity singleRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Spectrum = new Property(0, String.class, "spectrum", false, "SPECTRUM");
        public final static Property Lux = new Property(1, int.class, "Lux", false, "LUX");
        public final static Property Cct = new Property(2, int.class, "cct", false, "CCT");
        public final static Property Cri = new Property(3, int.class, "cri", false, "CRI");
        public final static Property X = new Property(4, float.class, "x", false, "X");
        public final static Property Y = new Property(5, float.class, "y", false, "Y");
        public final static Property Uv_u = new Property(6, float.class, "uv_u", false, "UV_U");
        public final static Property Uv_v = new Property(7, float.class, "uv_v", false, "UV_V");
        public final static Property Duv = new Property(8, float.class, "Duv", false, "DUV");
        public final static Property Dwave = new Property(9, int.class, "Dwave", false, "DWAVE");
        public final static Property Pwave = new Property(10, int.class, "Pwave", false, "PWAVE");
        public final static Property ColorRatio = new Property(11, float.class, "colorRatio", false, "COLOR_RATIO");
        public final static Property Rf = new Property(12, int.class, "Rf", false, "RF");
        public final static Property Rg = new Property(13, int.class, "Rg", false, "RG");
        public final static Property V = new Property(14, float.class, "V", false, "V");
        public final static Property Qa = new Property(15, String.class, "Qa", false, "QA");
        public final static Property Gai = new Property(16, int.class, "gai", false, "GAI");
        public final static Property Cqs = new Property(17, String.class, "cqs", false, "CQS");
        public final static Property RColor = new Property(18, int.class, "rColor", false, "R_COLOR");
        public final static Property GColor = new Property(19, int.class, "gColor", false, "G_COLOR");
        public final static Property BColor = new Property(20, int.class, "bColor", false, "B_COLOR");
        public final static Property PhotoPath = new Property(21, String.class, "photoPath", false, "PHOTO_PATH");
        public final static Property RecordTxtPath = new Property(22, String.class, "recordTxtPath", false, "RECORD_TXT_PATH");
        public final static Property Date = new Property(23, String.class, "date", true, "DATE");
    }


    public singleRecordDao(DaoConfig config) {
        super(config);
    }
    
    public singleRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SINGLE_RECORD\" (" + //
                "\"SPECTRUM\" TEXT," + // 0: spectrum
                "\"LUX\" INTEGER NOT NULL ," + // 1: Lux
                "\"CCT\" INTEGER NOT NULL ," + // 2: cct
                "\"CRI\" INTEGER NOT NULL ," + // 3: cri
                "\"X\" REAL NOT NULL ," + // 4: x
                "\"Y\" REAL NOT NULL ," + // 5: y
                "\"UV_U\" REAL NOT NULL ," + // 6: uv_u
                "\"UV_V\" REAL NOT NULL ," + // 7: uv_v
                "\"DUV\" REAL NOT NULL ," + // 8: Duv
                "\"DWAVE\" INTEGER NOT NULL ," + // 9: Dwave
                "\"PWAVE\" INTEGER NOT NULL ," + // 10: Pwave
                "\"COLOR_RATIO\" REAL NOT NULL ," + // 11: colorRatio
                "\"RF\" INTEGER NOT NULL ," + // 12: Rf
                "\"RG\" INTEGER NOT NULL ," + // 13: Rg
                "\"V\" REAL NOT NULL ," + // 14: V
                "\"QA\" TEXT," + // 15: Qa
                "\"GAI\" INTEGER NOT NULL ," + // 16: gai
                "\"CQS\" TEXT," + // 17: cqs
                "\"R_COLOR\" INTEGER NOT NULL ," + // 18: rColor
                "\"G_COLOR\" INTEGER NOT NULL ," + // 19: gColor
                "\"B_COLOR\" INTEGER NOT NULL ," + // 20: bColor
                "\"PHOTO_PATH\" TEXT," + // 21: photoPath
                "\"RECORD_TXT_PATH\" TEXT," + // 22: recordTxtPath
                "\"DATE\" TEXT PRIMARY KEY NOT NULL );"); // 23: date
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SINGLE_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, singleRecord entity) {
        stmt.clearBindings();
 
        String spectrum = entity.getSpectrum();
        if (spectrum != null) {
            stmt.bindString(1, spectrum);
        }
        stmt.bindLong(2, entity.getLux());
        stmt.bindLong(3, entity.getCct());
        stmt.bindLong(4, entity.getCri());
        stmt.bindDouble(5, entity.getX());
        stmt.bindDouble(6, entity.getY());
        stmt.bindDouble(7, entity.getUv_u());
        stmt.bindDouble(8, entity.getUv_v());
        stmt.bindDouble(9, entity.getDuv());
        stmt.bindLong(10, entity.getDwave());
        stmt.bindLong(11, entity.getPwave());
        stmt.bindDouble(12, entity.getColorRatio());
        stmt.bindLong(13, entity.getRf());
        stmt.bindLong(14, entity.getRg());
        stmt.bindDouble(15, entity.getV());
 
        String Qa = entity.getQa();
        if (Qa != null) {
            stmt.bindString(16, Qa);
        }
        stmt.bindLong(17, entity.getGai());
 
        String cqs = entity.getCqs();
        if (cqs != null) {
            stmt.bindString(18, cqs);
        }
        stmt.bindLong(19, entity.getRColor());
        stmt.bindLong(20, entity.getGColor());
        stmt.bindLong(21, entity.getBColor());
 
        String photoPath = entity.getPhotoPath();
        if (photoPath != null) {
            stmt.bindString(22, photoPath);
        }
 
        String recordTxtPath = entity.getRecordTxtPath();
        if (recordTxtPath != null) {
            stmt.bindString(23, recordTxtPath);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(24, date);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, singleRecord entity) {
        stmt.clearBindings();
 
        String spectrum = entity.getSpectrum();
        if (spectrum != null) {
            stmt.bindString(1, spectrum);
        }
        stmt.bindLong(2, entity.getLux());
        stmt.bindLong(3, entity.getCct());
        stmt.bindLong(4, entity.getCri());
        stmt.bindDouble(5, entity.getX());
        stmt.bindDouble(6, entity.getY());
        stmt.bindDouble(7, entity.getUv_u());
        stmt.bindDouble(8, entity.getUv_v());
        stmt.bindDouble(9, entity.getDuv());
        stmt.bindLong(10, entity.getDwave());
        stmt.bindLong(11, entity.getPwave());
        stmt.bindDouble(12, entity.getColorRatio());
        stmt.bindLong(13, entity.getRf());
        stmt.bindLong(14, entity.getRg());
        stmt.bindDouble(15, entity.getV());
 
        String Qa = entity.getQa();
        if (Qa != null) {
            stmt.bindString(16, Qa);
        }
        stmt.bindLong(17, entity.getGai());
 
        String cqs = entity.getCqs();
        if (cqs != null) {
            stmt.bindString(18, cqs);
        }
        stmt.bindLong(19, entity.getRColor());
        stmt.bindLong(20, entity.getGColor());
        stmt.bindLong(21, entity.getBColor());
 
        String photoPath = entity.getPhotoPath();
        if (photoPath != null) {
            stmt.bindString(22, photoPath);
        }
 
        String recordTxtPath = entity.getRecordTxtPath();
        if (recordTxtPath != null) {
            stmt.bindString(23, recordTxtPath);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(24, date);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23);
    }    

    @Override
    public singleRecord readEntity(Cursor cursor, int offset) {
        singleRecord entity = new singleRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // spectrum
            cursor.getInt(offset + 1), // Lux
            cursor.getInt(offset + 2), // cct
            cursor.getInt(offset + 3), // cri
            cursor.getFloat(offset + 4), // x
            cursor.getFloat(offset + 5), // y
            cursor.getFloat(offset + 6), // uv_u
            cursor.getFloat(offset + 7), // uv_v
            cursor.getFloat(offset + 8), // Duv
            cursor.getInt(offset + 9), // Dwave
            cursor.getInt(offset + 10), // Pwave
            cursor.getFloat(offset + 11), // colorRatio
            cursor.getInt(offset + 12), // Rf
            cursor.getInt(offset + 13), // Rg
            cursor.getFloat(offset + 14), // V
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // Qa
            cursor.getInt(offset + 16), // gai
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // cqs
            cursor.getInt(offset + 18), // rColor
            cursor.getInt(offset + 19), // gColor
            cursor.getInt(offset + 20), // bColor
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // photoPath
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // recordTxtPath
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23) // date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, singleRecord entity, int offset) {
        entity.setSpectrum(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLux(cursor.getInt(offset + 1));
        entity.setCct(cursor.getInt(offset + 2));
        entity.setCri(cursor.getInt(offset + 3));
        entity.setX(cursor.getFloat(offset + 4));
        entity.setY(cursor.getFloat(offset + 5));
        entity.setUv_u(cursor.getFloat(offset + 6));
        entity.setUv_v(cursor.getFloat(offset + 7));
        entity.setDuv(cursor.getFloat(offset + 8));
        entity.setDwave(cursor.getInt(offset + 9));
        entity.setPwave(cursor.getInt(offset + 10));
        entity.setColorRatio(cursor.getFloat(offset + 11));
        entity.setRf(cursor.getInt(offset + 12));
        entity.setRg(cursor.getInt(offset + 13));
        entity.setV(cursor.getFloat(offset + 14));
        entity.setQa(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setGai(cursor.getInt(offset + 16));
        entity.setCqs(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setRColor(cursor.getInt(offset + 18));
        entity.setGColor(cursor.getInt(offset + 19));
        entity.setBColor(cursor.getInt(offset + 20));
        entity.setPhotoPath(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setRecordTxtPath(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setDate(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
     }
    
    @Override
    protected final String updateKeyAfterInsert(singleRecord entity, long rowId) {
        return entity.getDate();
    }
    
    @Override
    public String getKey(singleRecord entity) {
        if(entity != null) {
            return entity.getDate();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(singleRecord entity) {
        return entity.getDate() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
